device:
    url: https://iomtfhir.azurehealthcareapis.com/Device1
    metadata:
      url: http://devicemetadataapidev.azurewebsites.net?csvDeviceIds=
fhir:
    authtoken: https://login.microsoftonline.com/ebd95286-551e-4b34-9fef-60b74293d1f9/oauth2/token
    clientId: 32a1883d-c8ba-446b-9d81-8fa2a829f62a
    clientSecret: 4UG_30zm~yt4wPkqb6GgY~C-35NEq3Id2C
    grantType: client_credentials
    resource: https://iomtfhir.azurehealthcareapis.com1
organization:
    url: organization=Organization/
patient:
    by:
        observation:
            prefix: ${patient.observation.url}?patient=Patient/
            suffix: '&code=8302-2,29463-7'
        organization:
            url:
                prefix: ${patient.url}?${organization.url}
                suffix: '&identifier='
        physician:
            suffix: '&${organization.url}'
            url: ${patient.url}?general-practitioner=Practitioner/
    count: _count=100
    identifier:
        url:
            std: http://hl7.org/fhir/sid/us-ssn
    observation:
        url: https://iomtfhir.azurehealthcareapis.com/Observation
    riskAss:
        suffix: ${patient.riskAssessment.url}?patient=Patient/
    riskAssessment:
        url: https://iomtfhir.azurehealthcareapis.com/RiskAssessment
    url: https://api.logicahealth.org/DSTUStandbox/data/Patient
